project_id = "yjulkjmrrawnjqvefizt"

[functions.create-admin-user]
verify_jwt = false

[functions.delete-admin-user]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.cancel-order]
verify_jwt = false

[functions.create-return-request]
verify_jwt = false
